// packages/vue/src/runtime/components/Panel.vue
<script setup lang="ts">
import { useStore } from "../store-inject.ts";
import ThreadDetail from "./ThreadDetail.vue";
import ThreadList from "./ThreadList.vue";

const store = useStore();

function close(): void {
  store.panelOpen.value = false;
}

function toggleResolved(): void {
  store.showResolved.value = !store.showResolved.value;
  void store.refreshThreads();
}
</script>

<template>
  <aside v-if="store.panelOpen.value" class="sn-panel">
    <header class="sn-panel-header">
      <h2>{{ store.openThreadId.value ? "Thread" : "Threads" }}</h2>
      <div class="sn-panel-actions">
        <button
          v-if="!store.openThreadId.value"
          type="button"
          :class="{ 'sn-active': store.showResolved.value }"
          @click="toggleResolved"
        >
          show resolved
        </button>
        <button type="button" @click="close">close</button>
      </div>
    </header>
    <div class="sn-panel-body">
      <ThreadDetail v-if="store.openThreadId.value" />
      <ThreadList v-else />
    </div>
  </aside>
</template>

// packages/react/src/runtime/components/Panel.tsx
import { useStore } from "../store.ts";
import ThreadDetail from "./ThreadDetail.tsx";
import ThreadList from "./ThreadList.tsx";

export default function Panel(): React.ReactElement | null {
  const panelOpen = useStore((s) => s.panelOpen);
  const openThreadId = useStore((s) => s.openThreadId);
  const showResolved = useStore((s) => s.showResolved);
  const setShowResolved = useStore((s) => s.setShowResolved);
  const closePanel = useStore((s) => s.closePanel);

  if (!panelOpen) return null;
  return (
    <aside className="sn-panel">
      <header className="sn-panel-header">
        <h2>{openThreadId ? "Thread" : "Threads"}</h2>
        <div className="sn-panel-actions">
          {!openThreadId ? (
            <button
              type="button"
              className={showResolved ? "sn-active" : ""}
              onClick={() => setShowResolved(!showResolved)}
            >
              show resolved
            </button>
          ) : null}
          <button type="button" onClick={closePanel}>
            close
          </button>
        </div>
      </header>
      <div className="sn-panel-body">{openThreadId ? <ThreadDetail /> : <ThreadList />}</div>
    </aside>
  );
}
