// packages/react/src/runtime/components/CommentForm.tsx
import { useRef, useState } from "react";

type Props = {
  initialBody?: string;
  submitLabel?: string;
  cancelable?: boolean;
  onSubmit: (body: string) => void;
  onCancel?: () => void;
};

export default function CommentForm(props: Props): React.ReactElement {
  const [body, setBody] = useState(props.initialBody ?? "");
  const formRef = useRef<HTMLFormElement | null>(null);

  const submit = (): void => {
    const text = body.trim();
    if (!text) return;
    props.onSubmit(text);
    setBody("");
  };

  const onKeyDown = (e: React.KeyboardEvent<HTMLTextAreaElement>): void => {
    if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
      e.preventDefault();
      formRef.current?.requestSubmit();
    }
  };

  return (
    <form
      ref={formRef}
      className="sn-form"
      onSubmit={(e) => {
        e.preventDefault();
        submit();
      }}
    >
      <textarea
        value={body}
        placeholder="Write a comment…"
        onChange={(e) => setBody(e.target.value)}
        onKeyDown={onKeyDown}
      />
      <div className="sn-form-actions">
        {props.cancelable ? (
          <button type="button" onClick={() => props.onCancel?.()}>
            cancel
          </button>
        ) : null}
        <button type="submit" className="sn-primary" disabled={!body.trim()}>
          {props.submitLabel ?? "Reply"}
        </button>
      </div>
    </form>
  );
}

// packages/vue/src/runtime/components/CommentForm.vue
<script setup lang="ts">
import { ref, useTemplateRef } from "vue";

const props = defineProps<{
  initialBody?: string;
  submitLabel?: string;
  cancelable?: boolean;
}>();
const emit = defineEmits<{
  submit: [body: string];
  cancel: [];
}>();

const body = ref(props.initialBody ?? "");
const formRef = useTemplateRef<HTMLFormElement>("formRef");

function submit(): void {
  const text = body.value.trim();
  if (!text) return;
  emit("submit", text);
  body.value = "";
}

function onKeydown(e: KeyboardEvent): void {
  if (e.key === "Enter" && (e.metaKey || e.ctrlKey)) {
    e.preventDefault();
    formRef.value?.requestSubmit();
  }
}
</script>

<template>
  <form ref="formRef" class="sn-form" @submit.prevent="submit">
    <textarea v-model="body" placeholder="Write a comment…" @keydown="onKeydown" />
    <div class="sn-form-actions">
      <button v-if="props.cancelable" type="button" @click="emit('cancel')">cancel</button>
      <button type="submit" class="sn-primary" :disabled="!body.trim()">
        {{ props.submitLabel ?? "Reply" }}
      </button>
    </div>
  </form>
</template>
