// examples/react/src/routes/about.tsx
import { createFileRoute } from "@tanstack/react-router";

export const Route = createFileRoute("/about")({
  component: AboutPage,
});

function AboutPage(): React.ReactElement {
  return (
    <section className="about">
      <h1>About</h1>
      <p>
        This page is just here to exercise route-aware threads. Drop pins on any element and they
        will only show on this route.
      </p>
      <style>{`.about { display: flex; flex-direction: column; gap: 12px; }`}</style>
    </section>
  );
}

// apps/website/src/pages/about.vue
<script setup lang="ts"></script>

<template>
  <section class="about">
    <h1>About</h1>
    <p>
      This page is just here to exercise route-aware threads. Drop pins on any element and they will
      only show on this route.
    </p>
  </section>
</template>

<style scoped>
.about {
  display: flex;
  flex-direction: column;
  gap: 12px;
}
</style>
